# Template for revision scripts
# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
import os

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '{{ revision }}'
down_revision: str | None = '{{ down_revision }}'
branch_labels: str | Sequence[str] | None = '{{ branch_labels }}'
depends_on: str | Sequence[str] | None = '{{ depends_on }}'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # !!! Custom code below !!!
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # !!! Custom code below !!!
    pass
    # ### end Alembic commands ###