"""add document type

Revision ID: 236278f35c80
Revises: b3f863980aee
Create Date: 2026-09-25 13:15:45.473869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236278f35c80'
down_revision: Union[str, Sequence[str], None] = 'b3f863980aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('embeddings_chunk_id_key'), 'embeddings', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('embeddings_chunk_id_key'), 'embeddings', ['chunk_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
