"""add chunk version uniqueness

Revision ID: b3f863980aee
Revises: f6479a21dd17
Create Date: 2026-09-20 16:02:38.480634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f863980aee'
down_revision: Union[str, Sequence[str], None] = 'f6479a21dd17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_chunks_document_version_index', 'chunks', ['document_id', 'index_version_id', 'chunk_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chunks_document_version_index', 'chunks', type_='unique')
    # ### end Alembic commands ###
