"""add document source metadata

Revision ID: 3813d8d517d7
Revises: 83d883a08035
Create Date: 2026-09-15 21:37:03.131247

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3813d8d517d7'
down_revision: Union[str, Sequence[str], None] = '83d883a08035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# PostgreSQL types used in this migration
_created_at_type = postgresql.TIMESTAMP(timezone=True)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_versions')
    op.add_column('documents', sa.Column('source_type', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('source_uri', sa.Text(), nullable=False))
    op.add_column('documents', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.drop_column('documents', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'documents',
        sa.Column(
            'source', sa.VARCHAR(), autoincrement=False, nullable=False,
        ),
    )
    op.drop_column('documents', 'external_id')
    op.drop_column('documents', 'source_uri')
    op.drop_column('documents', 'source_type')
    op.create_table(
        'document_versions',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column('created_at', _created_at_type, autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('document_versions_pkey')),
    )
    # ### end Alembic commands ###