"""create documents table

Revision ID: 76b79f0540cf
Revises: 8c04059a0aa6
Create Date: 2026-09-15 20:23:24.090568

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '76b79f0540cf'
down_revision: Union[str, Sequence[str], None] = '8c04059a0aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
